spring:
  main:
    banner-mode: off

  datasource:
    url: "jdbc:postgresql://localhost:5432/voting"
    username: "user"
    password: "password"

  sql:
    init:
      mode: always

  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: "UNSPECIFIED"
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        types.print.banner: false

server:
  port: 8080
  servlet:
    context-path: "/api"

logging:
  level:
    ru.smaginv.kvoting: debug
    org.springframework.cache: trace
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.orm.jpa.JpaTransactionManager: debug
  charset:
    console: UTF-8
  pattern:
    console: "%d{HH:mm:ss} %clr(%5p) %-65.65(%clr(%logger{50}){cyan}) : %msg%n"