spring:
  main:
    banner-mode: off

  datasource:
    url: "jdbc:postgresql://localhost:5432/voting"
    username: "user"
    password: "password"

  sql:
    init:
      mode: always

  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: "UNSPECIFIED"
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        types.print.banner: false

server:
  port: 8080
  servlet:
    context-path: "/api"

springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha

cache:
  entries: 1000
  heap-size: 1
  duration: 3600
  values:
    - "restaurant"
    - "vote"

format:
  date: "dd.MM.yyyy"
  date-time: "dd.MM.yyyy HH:mm:ss"

voting:
  end-vote-time: "11:00"

logging:
  level:
    ru.smaginv.kvoting: debug
    org.springframework.cache: trace
    org.springframework.web.servlet: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.orm.jpa.JpaTransactionManager: debug
  charset:
    console: UTF-8
  pattern:
    console: "%d{HH:mm:ss} %clr(%5p) %-65.65(%clr(%logger{50}){cyan}) : %msg%n"